// lib/mockTrends.ts - 트렌드 목업 데이터

import { TrendItem } from './types';

export const mockTrends: TrendItem[] = [
  {
    id: 'sora-shutdown-2026',
    title: 'OpenAI Sora 서비스 종료 발표',
    title_en: 'OpenAI Shuts Down Sora App and API',
    source: 'OpenAI Official',
    category: 'news',
    summary_ko:
      'OpenAI가 2026년 3월 24일 Sora 앱과 API 서비스 종료를 발표했습니다. 앱은 4월 26일, API는 9월 24일에 종료될 예정입니다.',
    importance: 'high',
    date: '2026-03-24',
    url: 'https://openai.com/index/sora-2/',
    keywords: ['OpenAI', 'Sora', '서비스종료', 'AI영상생성'],
  },
  {
    id: 'veo-3-1-updates',
    title: 'Google Veo 3.1 - 이미지로 비디오 생성',
    title_en: 'Google Veo 3.1 Ingredients to Video',
    source: 'Google DeepMind',
    category: 'technology',
    summary_ko:
      'Google의 Veo 3.1은 이미지를 표현력 있는 비디오로 변환할 수 있으며, 더 풍부한 대사와 일관된 캐릭터/배경을 지원합니다.',
    importance: 'high',
    date: '2026-03-15',
    url: 'https://blog.google/innovation-and-ai/technology/ai/veo-3-1-ingredients-to-video/',
    keywords: ['Google', 'Veo', '이미지투비디오', 'AI'],
  },
  {
    id: 'runway-gen-4-5-release',
    title: 'Runway Gen-4.5 - 최고의 비디오 모델 출시',
    title_en: 'Runway Gen-4.5 Released',
    source: 'Runway AI',
    category: 'technology',
    summary_ko:
      'Runway Gen-4.5는 현재 가장 우수한 비디오 모델로, Artificial Analysis 벤치마크에서 1위를 차지했습니다.',
    importance: 'high',
    date: '2025-12-15',
    url: 'https://runwayml.com/news',
    keywords: ['Runway', 'Gen-4.5', '벤치마크', '영상생성'],
  },
  {
    id: 'kling-2-6-voice-control',
    title: 'Kling 2.6 - 음성 제어와 모션 업그레이드',
    title_en: 'Kling 2.6 Adds Voice Control',
    source: 'Kling AI',
    category: 'technology',
    summary_ko:
      'Kling 2.6은 동시 오디오-비주얼 생성 기능을 도입하여 AI 영상 제작 워크플로우를 재정의합니다.',
    importance: 'high',
    date: '2026-03-20',
    url: 'https://the-decoder.com/kling-2-6/',
    keywords: ['Kling', '음성제어', '모션', 'AI영상'],
  },
  {
    id: 'seedance-2-0-bytedance',
    title: 'ByteDance Seedance 2.0 - 동시 오디오-비디오 생성',
    title_en: 'ByteDance Seedance 2.0',
    source: 'ByteDance',
    category: 'technology',
    summary_ko:
      'ByteDance의 Seedance 2.0은 최초로 오디오와 비디오를 동시에 8개 이상의 언어로 생성합니다. 2K 시네마 해상도를 지원합니다.',
    importance: 'high',
    date: '2026-02-10',
    url: 'https://techcrunch.com/2026/02/15/seedance-2-0/',
    keywords: ['ByteDance', 'Seedance', '오디오비디오', '2K'],
  },
  {
    id: 'ltx-2-production-grade',
    title: 'LTX-2 - 프로덕션급 4K 50fps 비디오 생성',
    title_en: 'LTX-2 Production-Grade AI Video',
    source: 'LTX Studio',
    category: 'technology',
    summary_ko:
      'LTX-2는 첫 번째 DiT 기반 오디오-비디오 파운데이션 모델로, 진정한 4K 50fps로 동기화된 오디오-비디오를 생성합니다.',
    importance: 'high',
    date: '2026-03-10',
    url: 'https://ltx.studio/blog/ltx-2',
    keywords: ['LTX', '4K', '50fps', 'DiT'],
  },
  {
    id: 'wan-2-2-open-source',
    title: 'Wan 2.2 - 오픈소스 MoE 비디오 생성 모델',
    title_en: 'Wan 2.2 Open-Source Video Model',
    source: 'Alibaba',
    category: 'technology',
    summary_ko:
      'Alibaba의 Wan 2.2는 오픈소스 모델로, RTX 4090 같은 소비자급 GPU에서 실행 가능합니다.',
    importance: 'medium',
    date: '2025-07-15',
    url: 'https://wan.video/',
    keywords: ['Alibaba', '오픈소스', 'MoE', 'GPU'],
  },
  {
    id: 'character-consistency-breakthrough',
    title: 'AI 영상의 캐릭터 일관성 문제 해결 진전',
    title_en: 'AI Character Consistency Breakthrough',
    source: 'VentureBeat',
    category: 'discussion',
    summary_ko:
      'Runway Gen-4, LTX Studio, Kling의 Elements 기능 등이 캐릭터 일관성 문제를 획기적으로 개선했습니다.',
    importance: 'high',
    date: '2026-02-01',
    url: 'https://venturebeat.com/ai/character-consistency/',
    keywords: ['캐릭터일관성', 'Runway', 'LTX', 'Kling'],
  },
  {
    id: 'reddit-consensus-multi-model-stack',
    title: 'Reddit AI 커뮤니티: 멀티 모델 스택 트렌드',
    title_en: 'Reddit Multi-Model Stack Trend',
    source: 'Reddit',
    category: 'discussion',
    summary_ko:
      'r/aivideo 커뮤니티에서 모듈식 스택 접근 방식으로 전환하는 트렌드가 관찰됩니다.',
    importance: 'medium',
    date: '2026-03-01',
    url: 'https://reddit.com/r/aivideo',
    keywords: ['Reddit', '멀티모델', '워크플로우', '커뮤니티'],
  },
  {
    id: 'ai-slop-problem-discussion',
    title: 'AI Slop 문제 - 저급 AI 생성 콘텐츠 증가',
    title_en: 'The AI Slop Problem',
    source: 'Reddit',
    category: 'discussion',
    summary_ko:
      'Reddit에서 AI Slop이라는 용어로 저급의 저노력 AI 콘텐츠를 묘사하고 있습니다.',
    importance: 'medium',
    date: '2026-02-15',
    url: 'https://reddit.com/r/aivideo',
    keywords: ['AI Slop', '품질', '콘텐츠', '비판'],
  },
  {
    id: 'copyright-issues-2026',
    title: 'AI 영상 생성과 저작권 문제: 2026 법적 진전',
    title_en: 'AI Copyright Issues 2026',
    source: 'Copyright Alliance',
    category: 'news',
    summary_ko:
      '2026년 3월 미국 대법원은 기계가 생성한 저작물은 저작권 보호 대상이 아니라고 확정했습니다.',
    importance: 'high',
    date: '2026-03-02',
    url: 'https://copyrightalliance.org/ai-copyright/',
    keywords: ['저작권', '대법원', '법률', 'AI생성물'],
  },
  {
    id: 'ai-video-hybrid-workflows',
    title: '하이브리드 AI 영상 제작 워크플로우 확산',
    title_en: 'Hybrid AI Video Workflows',
    source: 'X',
    category: 'discussion',
    summary_ko:
      'AI를 창의적 방향 설정의 도구로 보는 하이브리드 워크플로우가 확산되고 있습니다.',
    importance: 'high',
    date: '2026-02-20',
    url: 'https://ltx.studio/blog/hybrid',
    keywords: ['하이브리드', '워크플로우', '창작도구', 'AI'],
  },
  {
    id: 'ai-film-festival-2026',
    title: '2026 AI 국제 영화제 - 코스타 베르데 우승',
    title_en: 'AI International Film Festival 2026',
    source: 'AI Film Festival',
    category: 'news',
    summary_ko:
      '2026 AI 국제 영화제에서 프랑스 영화 코스타 베르데가 최고의 AI 영화상을 수상했습니다.',
    importance: 'medium',
    date: '2026-03-01',
    url: 'https://aifilmfest.org/',
    keywords: ['영화제', '코스타베르데', '수상', 'AI영화'],
  },
  {
    id: 'curious-refuge-ai-film-school',
    title: 'Curious Refuge - AI 영화제작 전문 온라인 학교',
    title_en: 'Curious Refuge AI Film School',
    source: 'Curious Refuge',
    category: 'news',
    summary_ko:
      'Curious Refuge는 AI 영화제작자들을 위한 최초의 온라인 학교로, 2026 Feel Good AI 영화 경연대회를 개최합니다.',
    importance: 'medium',
    date: '2026-03-31',
    url: 'https://curiousrefuge.com/',
    keywords: ['교육', 'CuriousRefuge', '영화제작', '경연대회'],
  },
  {
    id: 'transparency-disclosure-ai-video',
    title: 'AI 영상 제작의 투명성과 공개 필요성 강조',
    title_en: 'Transparency in AI Filmmaking',
    source: 'X',
    category: 'discussion',
    summary_ko:
      'AI 사용에 대한 투명성 태그, 명시적 면책조항, 동의 기반 데이터 공개가 업계의 핵심 이슈입니다.',
    importance: 'high',
    date: '2026-03-10',
    url: 'https://ltx.studio/blog/transparency',
    keywords: ['투명성', '공개', '윤리', 'AI사용'],
  },
  {
    id: 'real-time-video-generation-2026',
    title: '2026년 예상: 실시간 비디오 생성 모델 등장',
    title_en: 'Real-Time Video Generation 2026',
    source: 'Film Industry Analysis',
    category: 'discussion',
    summary_ko:
      '산업 전문가들은 2026년에 진정한 실시간 비디오 모델이 클라우드 기반으로 등장할 것으로 예측합니다.',
    importance: 'medium',
    date: '2026-03-15',
    url: 'https://ltx.studio/blog/trends',
    keywords: ['실시간', '비디오생성', '클라우드', '예측'],
  },
  {
    id: 'veo-3-canva-integration',
    title: 'Google Veo 3 - Canva와 통합되어 누구나 접근 가능',
    title_en: 'Google Veo 3 in Canva',
    source: 'Canva',
    category: 'technology',
    summary_ko:
      'Google의 Veo 3가 Canva에 통합되어 누구나 텍스트 프롬프트로 영화같은 비디오를 생성할 수 있게 되었습니다.',
    importance: 'medium',
    date: '2026-03-05',
    url: 'https://canva.com/veo3',
    keywords: ['Canva', 'Veo3', '대중화', '통합'],
  },
  {
    id: 'runway-api-third-party-models',
    title: 'Runway API - 타사 모델 통합 (Kling, Sora 등)',
    title_en: 'Runway API Third-Party Models',
    source: 'Runway AI',
    category: 'technology',
    summary_ko:
      'Runway는 자체 플랫폼에 Kling 3.0, Sora 2 Pro 등 타사 모델들을 통합했습니다.',
    importance: 'high',
    date: '2026-02-20',
    url: 'https://runwayml.com/api',
    keywords: ['Runway', 'API', '타사모델', '통합'],
  },
];
