// lib/prompt-score-mock.ts — Prompt Score 목 데이터

import { RankedFilm, DnaGapFilm, FameFilm } from './prompt-score-types';

export const mockRankedFilms: RankedFilm[] = [
  {
    id: '1',
    rank: 1,
    title: 'Neon Dreams: Digital Requiem',
    creator: 'Creative Studio X',
    thumbnailUrl: null,
    youtubeId: 'dQw4w9WgXcQ',
    promptScore: 94,
    audienceScore: 88,
    bloomStage: 'bloom',
    dna: { storytelling: 90, visual: 98, creativity: 95, promptDesign: 92, sound: 85 },
    dnaPattern: 'Visual Hunter',
    genre: ['sci-fi', 'drama'],
    aiTools: ['Sora', 'Midjourney'],
    reviewCount: 47,
    createdAt: '2026-03-25',
  },
  {
    id: '2',
    rank: 2,
    title: 'Echoes of Tomorrow',
    creator: 'LUNA AI Films',
    thumbnailUrl: null,
    youtubeId: 'dQw4w9WgXcQ',
    promptScore: 91,
    audienceScore: 82,
    bloomStage: 'bloom',
    dna: { storytelling: 96, visual: 88, creativity: 90, promptDesign: 85, sound: 92 },
    dnaPattern: 'Storyteller',
    genre: ['drama'],
    aiTools: ['Runway', 'ElevenLabs'],
    reviewCount: 38,
    createdAt: '2026-03-22',
  },
  {
    id: '3',
    rank: 3,
    title: 'The Last Cathedral',
    creator: 'Pixel Dreams Collective',
    thumbnailUrl: null,
    youtubeId: 'dQw4w9WgXcQ',
    promptScore: 88,
    audienceScore: 91,
    bloomStage: 'bloom',
    dna: { storytelling: 82, visual: 95, creativity: 88, promptDesign: 90, sound: 78 },
    dnaPattern: 'Composition Master',
    genre: ['fantasy'],
    aiTools: ['Kling', 'Stable Diffusion'],
    reviewCount: 33,
    createdAt: '2026-03-20',
  },
  {
    id: '4',
    rank: 4,
    title: '여우비',
    creator: '문라이트 스튜디오',
    thumbnailUrl: null,
    youtubeId: 'dQw4w9WgXcQ',
    promptScore: 85,
    audienceScore: 79,
    bloomStage: 'bloom',
    dna: { storytelling: 92, visual: 80, creativity: 85, promptDesign: 78, sound: 88 },
    dnaPattern: 'Emotion Designer',
    genre: ['drama', 'romance'],
    aiTools: ['Sora', 'Suno'],
    reviewCount: 29,
    createdAt: '2026-03-18',
  },
  {
    id: '5',
    rank: 5,
    title: 'Synthetic Horizons',
    creator: 'NeuralFrame Labs',
    thumbnailUrl: null,
    youtubeId: 'dQw4w9WgXcQ',
    promptScore: 82,
    audienceScore: 76,
    bloomStage: 'bloom',
    dna: { storytelling: 75, visual: 88, creativity: 90, promptDesign: 85, sound: 70 },
    dnaPattern: 'Tech Master',
    genre: ['sci-fi'],
    aiTools: ['Veo', 'Midjourney'],
    reviewCount: 25,
    createdAt: '2026-03-15',
  },
  {
    id: '6',
    rank: 6,
    title: '도깨비 시장',
    creator: 'AI 동화 공방',
    thumbnailUrl: null,
    youtubeId: 'dQw4w9WgXcQ',
    promptScore: 78,
    audienceScore: 85,
    bloomStage: 'bud',
    dna: { storytelling: 88, visual: 72, creativity: 80, promptDesign: 70, sound: 75 },
    dnaPattern: 'Storyteller',
    genre: ['fantasy', 'comedy'],
    aiTools: ['Runway', 'DALL-E'],
    reviewCount: 21,
    createdAt: '2026-03-14',
  },
  {
    id: '7',
    rank: 7,
    title: 'Binary Sunset',
    creator: 'Void Cinema',
    thumbnailUrl: null,
    youtubeId: 'dQw4w9WgXcQ',
    promptScore: 75,
    audienceScore: 72,
    bloomStage: 'bud',
    dna: { storytelling: 70, visual: 82, creativity: 78, promptDesign: 72, sound: 68 },
    dnaPattern: 'All-Rounder',
    genre: ['sci-fi', 'thriller'],
    aiTools: ['Pika', 'Midjourney'],
    reviewCount: 18,
    createdAt: '2026-03-12',
  },
  {
    id: '8',
    rank: 8,
    title: '미완의 계절',
    creator: '프레임 메이커즈',
    thumbnailUrl: null,
    youtubeId: 'dQw4w9WgXcQ',
    promptScore: 72,
    audienceScore: 68,
    bloomStage: 'bud',
    dna: { storytelling: 80, visual: 70, creativity: 72, promptDesign: 65, sound: 74 },
    dnaPattern: 'Emotion Designer',
    genre: ['drama'],
    aiTools: ['Luma', 'ElevenLabs'],
    reviewCount: 15,
    createdAt: '2026-03-10',
  },
  {
    id: '9',
    rank: 9,
    title: 'Fragments of Code',
    creator: 'Digital Alchemist',
    thumbnailUrl: null,
    youtubeId: 'dQw4w9WgXcQ',
    promptScore: 68,
    audienceScore: 65,
    bloomStage: 'bud',
    dna: { storytelling: 60, visual: 72, creativity: 75, promptDesign: 78, sound: 55 },
    dnaPattern: 'Tech Master',
    genre: ['documentary'],
    aiTools: ['Hailuo', 'Stable Diffusion'],
    reviewCount: 12,
    createdAt: '2026-03-08',
  },
  {
    id: '10',
    rank: 10,
    title: '밤의 정원사',
    creator: '시네마틱 AI',
    thumbnailUrl: null,
    youtubeId: 'dQw4w9WgXcQ',
    promptScore: 65,
    audienceScore: 70,
    bloomStage: 'bud',
    dna: { storytelling: 68, visual: 65, creativity: 62, promptDesign: 60, sound: 70 },
    dnaPattern: 'All-Rounder',
    genre: ['horror', 'fantasy'],
    aiTools: ['Kling', 'Suno'],
    reviewCount: 10,
    createdAt: '2026-03-05',
  },
];

export const mockDnaGapFilms: DnaGapFilm[] = [
  {
    id: '101',
    title: '인형의 꿈',
    creator: 'Shadow Works',
    thumbnailUrl: null,
    promptScore: 42,
    audienceScore: 78,
    gap: 36,
  },
  {
    id: '102',
    title: 'Algorithm of Love',
    creator: 'Neural Romance Studio',
    thumbnailUrl: null,
    promptScore: 88,
    audienceScore: 55,
    gap: 33,
  },
  {
    id: '103',
    title: 'Pixel Decay',
    creator: 'GlitchFrame',
    thumbnailUrl: null,
    promptScore: 82,
    audienceScore: 54,
    gap: 28,
  },
];

export const mockFameFilms: FameFilm[] = [
  {
    id: '201',
    title: 'Genesis Protocol',
    creator: 'Apex AI Studio',
    thumbnailUrl: null,
    promptScore: 97,
    bloomStage: 'bloom',
    badges: ['Super Bloom', 'Visual DNA'],
  },
  {
    id: '202',
    title: '천 개의 눈',
    creator: 'Dreamscape Korea',
    thumbnailUrl: null,
    promptScore: 95,
    bloomStage: 'bloom',
    badges: ['Super Bloom', 'Story DNA'],
  },
  {
    id: '203',
    title: 'The Prompt Architect',
    creator: 'Metaframe Collective',
    thumbnailUrl: null,
    promptScore: 93,
    bloomStage: 'bloom',
    badges: ['Full Bloom', 'Tech DNA'],
  },
  {
    id: '204',
    title: '산책하는 AI',
    creator: '모닝스타 필름',
    thumbnailUrl: null,
    promptScore: 92,
    bloomStage: 'bloom',
    badges: ['Full Bloom', 'Hidden Gem'],
  },
];
